### ISSUE TITLE
Need to be able to punch when no weapons in inventory.

### ISSUE THREAD

**Issue by ZenDragonX** [Terrenteller/ValheimMods#2]
Hi, NoUnarmedCombat is a great mod!   But there is a problem:  When first starting the game with a new character or after dying and respawning there are no weapons in the inventory.  In the situation where there are no weapons to equip it should allow the player to punch and kick as usual.

**Comment by Terrenteller** [comment]
Completed with 4b54b19e69ea1ba88eb6c2ca28d488bcec826340. Thank you for the suggestion.
