### ISSUE TITLE
[Question][RestfulArrival] Does the mod apply a resting bonus to a player who has logged out and then back in?

### ISSUE THREAD

**Issue by Magnacoder** [Terrenteller/ValheimMods#4]
Is it possible for players to cheat with this mod by logging out unrested and then logging back in to reach rested status without waiting the rested time?

(ours is 15 seconds, which is silly in the practical sense, but what if we set our rested configuration to 60 seconds for example)

**Comment by Terrenteller** [comment]
Yes. This mod being a cheat depends entirely on whether the player can re-join before the rested buff is normally applied (and the tedium of re-joining is worthwhile).
